version: '3'

services:
  account_main:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/code
      - ./docker/shared:/shared
      - ./docker/data/app_venv:/venv3
      - ./docker/data/home/app:/root
    networks:
      - account_net
      - nats_net
    depends_on:
      - account_db
    env_file:
      - .env
    ports:
      - ${UVICORN_MAP_PORT}:${UVICORN_MAP_PORT}

  account_db:
    env_file:
      - .env
    image: postgres:12
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
      - ./docker/shared/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/shared:/shared
    ports:
      - 5432:${DB_PORT}
    networks:
      - account_net

networks:
  account_net:
    name: account_net
  nats_net:
    name: nats_net